# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=39.99),
        ),
    ]
